site_name: MESH documentation
site_author: Kaifeng Chen

repo_url: https://github.com/kfrancischen/MESH

python:
   version: 2 # for unicode
   setup_py_install: true

#the third-party extenison mdx_math.py comes with a setup.py script
# Thank you Dmitry Shachnev (https://github.com/mitya57/python-markdown-math)
markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True #for use of inline $..$
    - fenced_code
    - codehilite
    - footnotes
    - admonition
    - toc(permalink=true)

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML', 'mathjaxhelper.js']

pages:
- Home: 'index.md'
- Overview:
  - 'Equations & Features': 'features.md'
  - 'Installation': 'installation.md'
- Lua API:
  - 'Base Class': 'LuaAPI/baseClass.md'
  - 'SimulationPlanar': 'LuaAPI/planar.md'
  - 'SimulationGrating': 'LuaAPI/grating.md'
  - 'SimulationPattern': 'LuaAPI/pattern.md'
- C++ API:
  - 'Classes and Functions': 'C++API/classAndFunction.md'
- Examples:
  - 'Tutorial Example': 'Examples/tutorial.md'
  - 'Single Plane Far-field': 'Examples/planeFarField.md'
  - 'Two Planes Near-field': 'Examples/planeNearField.md'
  - 'Anisotropic Material Near-field': 'Examples/anisotropic.md'
  - 'Iterate Over Gaps Near-field': 'Examples/iterate.md'
  - 'Two Gratings Near-field': 'Examples/gratingNearField.md'
  - 'Two Rectangle Patterns Near-field': 'Examples/rectangleNearField.md'
  - 'Mixed Patterns Near-field': 'Examples/mixedNearField.md'
  - 'MPI Example': 'Examples/MPI.md'
- Developer: 'develop.md'
- About: 'about.md'

theme: 'material'
